const NEW_BULK = "NEW_BULK";
const SEND_TO_DYEING_BULK = "SEND_TO_DYEING_BULK";
const RECEIVE_FROM_DYEING_BULK = "RECEIVE_FROM_DYEING_BULK";

module.exports = {
    NEW_BULK,
    SEND_TO_DYEING_BULK,
    RECEIVE_FROM_DYEING_BULK
}